### ISSUE TITLE
Call to a member function getRolesByUser() on boolean

### ISSUE THREAD

**Issue by smck87** [webvimark/user-management#104]
After I did log in via Login form I am getting this error:
```
PHP Fatal Error – yii\base\ErrorException
Call to a member function getRolesByUser() on boolean
```
After refreshing the page all seems fine: user is loged in.

Here is full listing of the error:
http://www.picshare.ru/uploads/151228/Qq89iqyTBb.png

![Error listing](http://www.picshare.ru/uploads/151228/Qq89iqyTBb.png)

**Comment by webvimark** [comment]
Hi, sorry for late response. You need to update module
