### ISSUE TITLE
After login it redirect on same login page

### ISSUE THREAD

**Issue by vkonde** [webvimark/user-management#107]
user-management extension install correctly but there is a problem with login it redirect on same login page(It's login perfectly i.e entry in user_visit_log table done) but not redirecting and one more thing ,
How can i change permission and Role also play with users.(By URL)

Thank you,

**Comment by vkonde** [comment]
My behaviors() is in SiteController 
public function behaviors()
{
    return [
        'ghost-access'=> [
            'class' => 'webvimark\modules\UserManagement\components\GhostAccessControl',
        ],
    ];
}

**Comment by vkonde** [comment]
Can not redirect to any other url i.e 
/user-management/auth/registration
/user-management/auth/permission
/user-management/auth/logout

**Comment by msankar1991** [comment]
I'm also getting same issue after login it redirect on same login page
