### ISSUE TITLE
Change view login

### ISSUE THREAD

**Issue by lukBarros** [webvimark/user-management#125]
Change view login. It is possible?

**Comment by vipuleheuristic** [comment]
Yes it is.

**Comment by meszarosk** [comment]
How can you do that without changing of module view file?

**Comment by webvimark** [comment]
Hi, here is the guide for customizing views without changing initial files - http://www.yiiframework.com/doc-2.0/guide-output-theming.html

**Comment by meszarosk** [comment]
Hi webvimark
I've read this manual, but failed to set a working solution.
Could you tell me what's the pathMap 'key' ? It's not clear to me...

`    'components' => [
		 'view' => [
				'theme' => [
					'pathMap' => [
						'@vendor/webvimark/modules/module-user-management/views' => '@backend/view/user-management/',  
					],
				],
		],		
`

Thanks again!

**Comment by webvimark** [comment]
With your config you can add in to folder **@backend/view/user-management/** additional folder **auth** and there create login.php file
`

**Comment by meszarosk** [comment]
Great! Thanks!
There were some mistyped but with your instruction it's working:

`    'components' => [

                 'view' => [
                                'theme' => [
                                        'pathMap' => [
                                                '@vendor/webvimark/module-user-management/views/' => '@backend/views/user-management/',  
                                        ],
                                ],
                ], `

**Comment by webvimark** [comment]
you are welcome =)
