### ISSUE TITLE
Error : Method Not Allowed (#405) 

### ISSUE THREAD

**Issue by vipuleheuristic** [webvimark/user-management#128]
By using webvimark , first time login we are getting this error and next try it will worked.
same problem is in deleting user in user listing of webvimark the same error occurs.
i am not getting what is the problem. any help appreciated.

**Comment by webvimark** [comment]
Hi, try to run composer update. This issue fixed in one dependency (webvimark/components)

**Comment by vipuleheuristic** [comment]
ohk let me try @webvimark

**Comment by vipuleheuristic** [comment]
still the problem exists @webvimark

**Comment by webvimark** [comment]
Tank you for pointing at the problem.
Run composer update again, it should work now

**Comment by vipuleheuristic** [comment]
Hello @webvimark , Thank you so much. Its working now :+1:

**Comment by vipuleheuristic** [comment]
hello @webvimark the same problem occurs again.

**Comment by webvimark** [comment]
Hi, need more data. You update packages and have this error when try to
delete users from the gridview?
12 Июл 2016 г. 7:38 пользователь "vipuleheuristic" <notifications@github.com>
написал:

**Comment by vipuleheuristic** [comment]
No this time i am not getting error while deleting user but only when first time login.

**Comment by webvimark** [comment]
Could you enable YII_DEBUG send me screenshot with stacktrace when error occurs ?

**Comment by vipuleheuristic** [comment]
for now the problem looks to be solved. @webvimark :+1:

**Comment by webvimark** [comment]
OK =) But if it will occurs again, try to get stacktrace and attach it here

**Comment by vipuleheuristic** [comment]
ok =) @webvimark

**Comment by vipuleheuristic** [comment]
Hello @webvimark the same problem of Bad Request #400 occurs while first time login my another YII2 App having the same problem. Webvimark Version : 1.0.5.
![webvimark_login_issue](https://cloud.githubusercontent.com/assets/16426817/17016343/5d4211b2-4f4c-11e6-970c-46c1b7f2f190.png)
