### ISSUE TITLE
migrations with postgresql

### ISSUE THREAD

**Issue by lebarjack** [webvimark/user-management#13]
I had to replace tinyint (not supported in postgresql) by smallint(1) in m140608_173539_create_user_table.php and m141201_220516_add_email_and_email_confirmed_to_user.php

I had another problem while bootstrapping the initial tables when adding the superadmin user (m140809_072112_insert_superadmin_to_user.php). I had to drop the NOT NULL constraint in user.authkey.

**Comment by webvimark** [comment]
Fixed. I think >_<
