### ISSUE TITLE
Permission to Roles - Webvimark login

### ISSUE THREAD

**Issue by vipuleheuristic** [webvimark/user-management#130]
What is the correct way to give permission to only specific roles to webvimark login without changing in vendor folder.

**Comment by webvimark** [comment]
Hmm, login action is free to access for everyone, because guests has no role (they are not logged in). And when user is logged in he will be automatically redirected to home page if he will try to access it.

Or I did not understand your question ?

**Comment by vipuleheuristic** [comment]
Let me explain,
Suppose i am having user roles as
Superadmin,
Employee,
Customer,
End User

and suppose i want only superadmin and employee to access the WEBVIMARK login. so what to do for that

**Comment by webvimark** [comment]
Unfortunately there are no such options. But you can try to rewrite LoginForm and add there your custom logic. For this you have to add this to index.php after line where you require composer autolader

`Yii::$classMap['webvimark\modules\UserManagement\models\forms\LoginForm'] = '\somewhere\CustomLoginForm'`

**Comment by vipuleheuristic** [comment]
okay @webvimark
