### ISSUE TITLE
Error migrate m141207_001649_create_basic_user_permissions

### ISSUE THREAD

**Issue by sallfris** [webvimark/user-management#135]
Yii2 version 2.0.9

*** applying m141207_001649_create_basic_user_permissions
Exception: Setting unknown property: yii\rbac\PhpManager::modelClass (D:\OpenServer\domains\s-san.dev\vendor\yiisoft\yii2\base\Component.php:197)
#0 D:\OpenServer\domains\s-san.dev\vendor\yiisoft\yii2\BaseYii.php(521): yii\base\Component->__set('modelClass', 'app\\models\\user...')
#1 D:\OpenServer\domains\s-san.dev\vendor\yiisoft\yii2\base\Object.php(105): yii\BaseYii::configure(Object(yii\rbac\PhpManager), Array)
#2 [internal function]: yii\base\Object->__construct(Array)
#3 D:\OpenServer\domains\s-san.dev\vendor\yiisoft\yii2\di\Container.php(379): ReflectionClass->newInstanceArgs(Array)
#4 D:\OpenServer\domains\s-san.dev\vendor\yiisoft\yii2\di\Container.php(154): yii\di\Container->build('yii\\rbac\\PhpMan...', Array, Array)
#5 D:\OpenServer\domains\s-san.dev\vendor\yiisoft\yii2\BaseYii.php(344): yii\di\Container->get('yii\\rbac\\PhpMan...', Array, Array)
#6 D:\OpenServer\domains\s-san.dev\vendor\yiisoft\yii2\di\ServiceLocator.php(133): yii\BaseYii::createObject(Array)
#7 D:\OpenServer\domains\s-san.dev\vendor\yiisoft\yii2\di\ServiceLocator.php(71): yii\di\ServiceLocator->get('authManager')
#8 D:\OpenServer\domains\s-san.dev\vendor\webvimark\module-user-management\models\rbacDB\AbstractItem.php(88): yii\di\ServiceLocator->__get('authManager')
#9 D:\OpenServer\domains\s-san.dev\vendor\webvimark\module-user-management\migrations\m141207_001649_create_basic_user_permissions.php(65): webvimark\modules\UserManagement\models\rbacDB\AbstractItem::addChildren('assignRolesToUs...', Array)
#10 D:\OpenServer\domains\s-san.dev\vendor\yiisoft\yii2\db\Migration.php(93): m141207_001649_create_basic_user_permissions->safeUp()
#11 D:\OpenServer\domains\s-san.dev\vendor\yiisoft\yii2\console\controllers\BaseMigrateController.php(509): yii\db\Migration->up()
#12 D:\OpenServer\domains\s-san.dev\vendor\yiisoft\yii2\console\controllers\BaseMigrateController.php(130): yii\console\controllers\BaseMigrateController->migrateUp('m141207_001649_...')
#13 [internal function]: yii\console\controllers\BaseMigrateController->actionUp(0)
#14 D:\OpenServer\domains\s-san.dev\vendor\yiisoft\yii2\base\InlineAction.php(55): call_user_func_array(Array, Array)
#15 D:\OpenServer\domains\s-san.dev\vendor\yiisoft\yii2\base\Controller.php(154): yii\base\InlineAction->runWithParams(Array)
#16 D:\OpenServer\domains\s-san.dev\vendor\yiisoft\yii2\console\Controller.php(119): yii\base\Controller->runAction('', Array)
#17 D:\OpenServer\domains\s-san.dev\vendor\yiisoft\yii2\base\Module.php(454): yii\console\Controller->runAction('', Array)
#18 D:\OpenServer\domains\s-san.dev\vendor\yiisoft\yii2\console\Application.php(180): yii\base\Module->runAction('migrate', Array)
#19 D:\OpenServer\domains\s-san.dev\vendor\yiisoft\yii2\console\Application.php(147): yii\console\Application->runAction('migrate', Array)
#20 D:\OpenServer\domains\s-san.dev\vendor\yiisoft\yii2\base\Application.php(375): yii\console\Application->handleRequest(Object(yii\console\Request))
#21 D:\OpenServer\domains\s-san.dev\yii(25): yii\base\Application->run()
#22 {main}
*** failed to apply m141207_001649_create_basic_user_permissions (time: 0.150s)

0 from 1 migrations were applied.

Migration failed. The rest of the migrations are canceled.

**Comment by szabozoltan69** [comment]
I had similar problem.
(It seems to be too long command sequence, maybe the transaction tracer loose the track... 
For me it was at SELECT EXISTS(SELECT * FROM "auth_item" WHERE "name"='viewUserRoles'),
so m141207_001649_create_basic_user_permissions.php(58).)

Until this the $this->pdoStatement contained the $rawSql and the rowCount, but a few records before the erroneous one this object became empty. I don't know the reason.

My solution was an abbreviation of  m141207_001649_create_basic_user_permissions.php, via commenting the Permission::assignRoutes part, and putting it to a next pseudo-migration file, m141207_001650_create_basic_user_permissionz, like this. Any nicer solution would be appreciated.

`class m141207_001650_create_basic_user_permissionz extends Migration
{
        public function safeUp()
        {
                Route::refreshRoutes();

                Role::create('Admin');

                // ================= User management permissions =================
                $group = new AuthItemGroup();
                $group->name = 'User management';
                $group->code = 'userManagement';


                Permission::assignRoutes('viewVisitLog', [
                        '/user-management/user-visit-log/index',
                        '/user-management/user-visit-log/grid-page-size',
                        '/user-management/user-visit-log/view',
                ], 'View visit log', $group->code);
        }

        public function safeDown()
        {
                echo "Don't do anything in this hack";
        }
}`

**Comment by unrealmach** [comment]
I think that for some reason the ORM is freezing the transaction with each entry of authitemgroup and its children.

I fix the error:
1.- customizing migrations, copying from the vendor, and placing them in a directory in my project.
2. dividing the problematic migration (create_basic_user_permission) in each authitemgroup having in total 3 files.
So far it works fine in PostgreSQL
