### ISSUE TITLE
Getting unknown property: yii\web\User::isSuperadmin

### ISSUE THREAD

**Issue by ianpierreg** [webvimark/user-management#142]
Why am I getting this error? 

I did everything the tutorial shows, the way the tutorial shows.

**Comment by webvimark** [comment]
Nope, you didn't =) Because as I see it from your error, you haven't set user component in config. You still have old *yii\web\User*

**Comment by kevindaus** [comment]
@ianpierreg = can you paste our configuration file... the code inside config/web.php ...

**Comment by ianpierreg** [comment]
My bad guys. I actually duplicated the user entry. Thx anyway!
