### ISSUE TITLE
LittleBigHelper bug 

### ISSUE THREAD

**Issue by kevindaus** [webvimark/user-management#143]
LittleBigHelper class

line 118

```
		if (php_sapi_name() == 'cli')
		{
			return $ip;
		}
```

causes  "Integrity constraint violation: 1048 Column 'ip' cannot be null error"
during testing . 
it occurs when I have to login inside my test and I have this in my configuration file
```
        'user' => [
            'class' => \app\components\UserIdentity::className(),
            'on afterLogin' => function ($event) {
                \webvimark\modules\UserManagement\models\UserVisitLog::newVisitor($event->identity->id);
            },
            'loginUrl'=>'/login'
        ],
```

**Cause** 
null is returned but IP column is required. I think it would be ok  if the returned ip would be **'127.0.0.1'** instead of null

would be ok if it will changed to 

```
		if (php_sapi_name() == 'cli')
		{
			return "127.0.0.1";
		}
```

**Comment by webvimark** [comment]
Hmm, looks like a good idea. If you use it from console - it's obivious is a local IP.
I'll make changes tomorrow

**Comment by webvimark** [comment]
You can now do composer update
