### ISSUE TITLE
Free Access to user

### ISSUE THREAD

**Issue by vipullakhtariya** [webvimark/user-management#145]
Hello 
i have created a some controllers and models now when i access them it redirects me to user login.
i have given free access and allowed in common permission still the same problem.
Can you help me out?

**Comment by webvimark** [comment]
Can you show me beginning of the controller class

**Comment by vipullakhtariya** [comment]
`class ApiController extends \yii\web\Controller {`

**Comment by webvimark** [comment]
No, I mean beginning of the controller including attributes like public $freeAccess = true; and behaviors block

**Comment by vipullakhtariya** [comment]
got the another solution :-)

**Comment by webvimark** [comment]
ok )

**Comment by CARLOS-DANIEL-ANGEL-PADILLA** [comment]
Hello, I have the same problem and I still do not know how to solve it, the code of my controller is as follows.

```
class SiteController extends Controller {

    /**
     * {@inheritdoc}
     */
    
    public $freeAccess= true;
        
    public function behaviors() {
        
        return [
            
            'ghost-access' => [
                'class' => 'webvimark\modules\UserManagement\components\GhostAccessControl',
            ],
            
        ];
        
    }
```
