### ISSUE TITLE
Custom Permission

### ISSUE THREAD

**Issue by vipullakhtariya** [webvimark/user-management#153]
Hello 
i am having user roles as follows:
1. bussinessAdmin
2. Customer
3. Employeee
4. Superadmin

and having table
Events

now i want to show events that only created by businessAdmin not by other users when businessAdmin logs in.
so is there any way to do that by this extension ?

**Comment by Stunc0** [comment]
Hi, 

No i don't think so.
You need to associate it with a behavior like  yii\behaviors\BlameableBehavior on your Event class.(see [http://www.yiiframework.com/doc-2.0/yii-behaviors-blameablebehavior.html](url))

Once you do that you will be abble to that by filtering your events on created_id.

**Comment by webvimark** [comment]
Thanks @Stunc0
