### ISSUE TITLE
Getting unknown property: yii\web\User::IsSuperadmin

### ISSUE THREAD

**Issue by roopeshpdit** [webvimark/user-management#157]
Getting this problem when i run extension for the first time
Unknown Property – yii\base\UnknownPropertyException

Getting unknown property: yii\web\User::IsSuperadmin

![image](https://cloud.githubusercontent.com/assets/9152506/19649805/25110f86-99d5-11e6-965a-575383cbdae5.png)

**Comment by Stunc0** [comment]
Hi, 

I think you have the same problem than in this post [#142](https://github.com/webvimark/user-management/issues/142). Check your config.
