### ISSUE TITLE
RESTful API

### ISSUE THREAD

**Issue by jsgilvcb** [webvimark/user-management#16]
Is there a Way to use basic authentication or custom authentication for users in order to consume REST API done in a custom module ?.
I did implemented this tutorial https://github.com/yiisoft/yii2/blob/master/docs/guide/rest-controllers.md and fails when asking for an action named.

<name>Not Supported</name>
<message>"findIdentityByAccessToken" is not implemented.</message>
<code>0</code>
<type>yii\base\NotSupportedException</type>
<file>/Users/jsgil/Web/tpm/ws/vendor/webvimark/module-user-management/components/UserIdentity.php</file>
<line>38</line>

**Comment by webvimark** [comment]
Hi, check it now, I implemented this method

**Comment by jsgilvcb** [comment]
Excelente modulo. Gracias.
