### ISSUE TITLE
How to AJAX validation?

### ISSUE THREAD

**Issue by TomskDiver** [webvimark/user-management#17]
How to enablу AJAX validation on registration form? I add 'enableAjaxValidation' => true, but this don't work. Please show example.

**Comment by webvimark** [comment]
I've added ajax validation support. You may check it now

**Comment by TomskDiver** [comment]
I also already did it. But thanks anyway!

**Comment by TomskDiver** [comment]
AJAX validation breaks CAPTCHA. It always incorrect. See https://github.com/yiisoft/yii2/issues/6115

**Comment by webvimark** [comment]
I fixed it, you may check it now.
Thank you for details on this issue

**Comment by TomskDiver** [comment]
hmmm, don't worked. AJAX response always empty JSON []

**Comment by TomskDiver** [comment]
You are submitting a list of attributes is wrong in ActiveForm::validate($model, **$validateAttributes**);

**Comment by TomskDiver** [comment]
replace 
```php
$validateAttributes = $model->attributes;
unset($validateAttributes['captcha']);
```
with 
```php
$validateAttributes = $model->activeAttributes();
$key = array_search('captcha', $validateAttributes);
array_splice($validateAttributes, $key, 1);
```
AJAX validation be fixed!!! But in registration form after submit mark login red and show error ***Something went wrong***

**Comment by TomskDiver** [comment]
hmmm, registration worked with my changes. but you have error with check email when insert DB record. I'll see it tomorrow if you do not get better.
TIP: may be in form validation you check email as email confirmed? But in insert check email in excisting email and does not check for this mail confirmed? In form check validation ok, on insert error.
P.S. Sorry for my english:)

**Comment by TomskDiver** [comment]
see activerecord insert function. in if !$this->validate($attributes) always true. see model validate function it execute function hasErrors anв problem here.

**Comment by TomskDiver** [comment]
i found problem.
how to reproduce:
1. register user
2. try register another user but with the same email
You got message "Something went wrong". if debug you see E-mail "aaa@aaa.com" has already been taken

**Comment by webvimark** [comment]
I don't know how you implement it in your custom registration form, but you can check how I implemented email validation in User class.

```php
	/**
	 * Check that there is no such confirmed E-mail in the system
	 */
	public function validateEmailConfirmedUnique()
	{
		if ( $this->email )
		{
			$exists = User::findOne([
				'email'           => $this->email,
				'email_confirmed' => 1,
			]);

			if ( $exists AND $exists->id != $this->id )
			{
				$this->addError('email', UserManagementModule::t('front', 'This E-mail already exists'));
			}
		}
	}
```

**Comment by TomskDiver** [comment]
Maybe i make reg form wrong. Please make exmaple (i ask it in https://github.com/webvimark/user-management/issues/12)

**Comment by TomskDiver** [comment]
I find solution. In User model you set
['email', 'unique'],
['email', 'validateEmailConfirmedUnique'],
first validation (unique) is not necessary (wrong)!

**Comment by webvimark** [comment]
I've also started making example in https://github.com/webvimark/user-management/wiki/Registration-with-E-mail-as-login-and-required-confirmation (in progress - don't use as example yet).

So I'm closing issue and will leave feedback in in #12 when it's ready

**Comment by donmedo2000** [comment]
Hi, I just had my first encounter with the captcha issue in webvimark user management module. @TomskDiver, you're right. the validation keeps returning []. Workaround is this 
$validateAttributes = $model->attributes;
unset($validateAttributes['captcha']);
return ActiveForm::validate($model,$validateAttributes);

Change last line above to 

return ActiveForm::validate($model,array_keys($validateAttributes));
