### ISSUE TITLE
Registration and login and  password reset forms work together in single view 

### ISSUE THREAD

**Issue by anas-shehadeh** [webvimark/user-management#18]
I am using javascript fadeIn & Fadeout effect to show & hide the form. So to enable that effect i have to put all the three forms in a single view & have to call respective controllers(actionlogin, actionSignup & actionPasswordReset) on button click.
 and try to make it in one actionindex 
i have error 
Calling unknown method: app\controllers\AccController::triggerModuleEvent()
  in C:\xampp\htdocs\yesitis\vendor\yiisoft\yii2\base\Component.php

**Comment by webvimark** [comment]
I can only guess what may cause this problem (need to see your code), but I may suggest you to fix it fast by adding **triggerModuleEvent()** from AuthController in your AccController

**Comment by anas-shehadeh** [comment]
thanks
