### ISSUE TITLE
Login with Email 

### ISSUE THREAD

**Issue by anas-shehadeh** [webvimark/user-management#20]
i want make user login using Email 
and remove login with username

**Comment by webvimark** [comment]
See configuration properties $useEmailAsLogin and $emailConfirmationRequired

You just use username as e-mail

**Comment by PareshJain** [comment]
As mentioned by you, I have set the following parameters to true, but still login using email is not working.
	public $useEmailAsLogin = true;
        public $emailConfirmationRequired = true;

Do I need to change anything else?
