### ISSUE TITLE
Is this repository discontinued? 

### ISSUE THREAD

**Issue by micaelomota** [webvimark/user-management#204]
Guys, where is @webvimark ?
Is he alive? Who is maintaining this project?
The last merged pull request was in 2016, we've got 10 new opened merge requests and a lot of opened issues. 

I just forked that and I'm planning to maintain this if he doesn't appear...

**Comment by paskuale75** [comment]
Where's your forked? Can I add it on my project?

**Comment by micaelomota** [comment]
For those that might still be looking for it, here is https://packagist.org/packages/congenialbr/module-user-management
However I completely removed it from some of my projects and I'm using Yii2 native RBAC instead
