### ISSUE TITLE
Migration problem

### ISSUE THREAD

**Issue by claudiogg88** [webvimark/user-management#21]
Good Day,

i try to run migration commands after configurations and got this message, could help me?

![sin titulo](https://cloud.githubusercontent.com/assets/7227926/6475441/f9c9de90-c1e8-11e4-8f91-8cdaa7c73a84.jpg)

**Comment by webvimark** [comment]
Done, you may check now

**Comment by Stefan39** [comment]
On a new project i got the same error on migration with the current version.
