### ISSUE TITLE
UserManagementModule path

### ISSUE THREAD

**Issue by w84gg** [webvimark/user-management#22]
Hello! 
in file 
https://github.com/webvimark/user-management/blob/master/views/auth/registration.php

I think it's uncorrect path for module

"use webvimark\modules\UserManagement\UserManagementModule;" at line 3

Could you help please? It seems this module not works because of invalid path

**Comment by anas-shehadeh** [comment]
it is correct path

**Comment by webvimark** [comment]
Could you please describe how you installed this module and show me exact error (may be attach screenshot)
