### ISSUE TITLE
Error install

### ISSUE THREAD

**Issue by danilz** [webvimark/user-management#25]
Hello.
I recently started using composer, and when you install the following error:
- The requested package webvimark/module-user-management could not be found in any version, there may be a typo in the package name.
Thank you.

**Comment by danilz** [comment]
And where to get the schema.mysql.sql?

**Comment by webvimark** [comment]
About composer check this post - http://www.yiiframework.com/forum/index.php/topic/60410-yii2-user-management-module/page__view__findpost__p__270905

And there is migrations, not schema.mysql.sql :)

**Comment by webvimark** [comment]
Also added mysql.schema.sql in migrations folder
