### ISSUE TITLE
Showing roles assigned to selected user, not current user. (user-management/user/view)

### ISSUE THREAD

**Issue by krystian-thiede** [webvimark/user-management#26]
Hi, 

Your module is an excellent work. I have a suggestion to a user/view part.

When you register as the superadmin, create a user, you see all available roles for selected user if you on a path user/view, e.g: user-management/user/view?id=8. I think that in this place superadmin or another user with correct rights should see only roles assigned to selected user like on user/update path. Do you agree?

The problem lies here: vendor\webvimark\module-user-management\views\user\view.php:67). Role::getAvailableRoles() should be replace with Role::getUserRoles().

Thanks in advance for an answer!

**Comment by webvimark** [comment]
Fixed.
Thank you, for pointing at this bug :)
