### ISSUE TITLE
Migration User table Creation

### ISSUE THREAD

**Issue by pabloamg** [webvimark/user-management#31]
Hi, when i run ./yii migrate --migrationPath=vendor/webvimark/module-user-management/migrations/

i get this

![image](https://cloud.githubusercontent.com/assets/5544771/6705560/b56850c2-cd1b-11e4-991f-0f130af179bc.png)

could you help me? 

thanks in advance.

**Comment by webvimark** [comment]
Hi, for some reason Yii::$app->getModule('user-management')->user_table returns empty value in your example.

You can use mysql.schema.sql in migrations/ folder 

Try it and if there are will be problems I'll look in to it when will be back from vacation

**Comment by pabloamg** [comment]
Hi,Thanks for your reply.

in step 2 in the installation help says: "2) In your config/console.php (this is needed for migrations and working with console)"

i assume you mean to put it in common/config/console.php ? or is that for the basic template?
in advanced that file needs to be created but i dont think yii actually reads it, so i put
```
'modules'=>[
    'user-management' => [
        'class' => 'webvimark\modules\UserManagement\UserManagementModule',
    ],
],
```

inside of advanced/console/config/main-local.php and then the migration works without a problem, strange thing is that the error was not about not founding the module but returning the name empty as you said.


Thanks again.

**Comment by webvimark** [comment]
Yep, guide was made for basic template, but you made write choice for putting this code in to the advanced/console/config/main-local.php :)
