### ISSUE TITLE
Duplicate error on creating role

### ISSUE THREAD

**Issue by oklimm** [webvimark/user-management#32]
Duplicate error on creating role if permission with the same name already exists, and vice versa

**Comment by webvimark** [comment]
Hi, this module uses yii2 built-in rbac system and it's architecture. All roles, permissions and routes are stored in the same table

**Comment by oklimm** [comment]
But when we are trying to create a second permission with the same name, a message appears
![error1](https://cloud.githubusercontent.com/assets/10355874/6827120/bce623be-d316-11e4-8256-c3cc218e3010.png)
The same message we get if we try to create two roles with the same name.
But on creating a role with the same name as permission has, we get error
![error2](https://cloud.githubusercontent.com/assets/10355874/6827288/a74b1a68-d317-11e4-89df-de5a867995d3.png)

**Comment by webvimark** [comment]
Fixed it, thank you for pointing on this issue
