### ISSUE TITLE
Access to model function

### ISSUE THREAD

**Issue by Boco10** [webvimark/user-management#33]
PHP Fatal Error – yii\base\ErrorException
Call to a member function getVacationDays() on a non-object

    1. in C:\xampp\htdocs\ADMINLTE2\backend\views\site\_userCalendar.php at line 34
    25262728293031323334353637383940414243

                                        ]);
     
                                    echo "<div id='modalContent'> </div>";
     
                                    Modal::end();
                         ?> 
     
     
                                 <?= \yii2fullcalendar\yii2fullcalendar::widget(array(
                                            'events'=>$model->getVacationDays(),
                                            'options' => [
                                                    'id' => 'DashBoardCalendar',
                                                    'class' => 'DashboardCalendarClass',
                                            ],
                                            'header' => [
                                                'left' => 'title',
                                                'center' => '',
                                                'right:' =>  'today prev,next'
                                            ],

This is currently the site/index which the user has access.
 /site/error
/site/index
 /user-vacation-days/create
/user-vacation-days/create-with-attributes
/user-vacation-days/delete
/user-vacation-days/full-calendar
/user-vacation-days/index
/user-vacation-days/index-ajax
/user-vacation-days/proceed-request
/user-vacation-days/request
/user-vacation-days/save-new-vacation
/user-vacation-days/update
/user-vacation-days/update-partion
/user-vacation-days/view

$model =  UserVacationDays::findOne(['user'=>Yii::$app->user->id])

What am i doing wrong? How can i call that function ?

**Comment by webvimark** [comment]
Hey, I think you choose wrong repository =)
How it's related to user-management module ?

**Comment by Boco10** [comment]
Because i can reach that function with superuser, but with the other user i don't.

**Comment by Boco10** [comment]
So basically my problem is. I've added the right to reach the controller function, which renders the view, and pass the model. But if i call a model function in the view, its not allowed, as it seems.

**Comment by webvimark** [comment]
It seems you just don't have records in UserVacationDays for that user.

```
PHP Fatal Error – yii\base\ErrorException
Call to a member function getVacationDays() on a non-object
```

It's clearly tells that $model is empty (NULL) and you trying to access some method from null object

**Comment by Boco10** [comment]
True bad, my bad. Sorry :(
