### ISSUE TITLE
Email message translations

### ISSUE THREAD

**Issue by croccav** [webvimark/user-management#36]
Hi Webvimark, thanks for your work.

I would like to offer Spanish translation if you tell me how to upload it. I have the files but I'm new to git and not sure how the "pull requests" work.

Also, I would like to add translations to email messages. For example:
registrationEmailConfirmation.php, line 13
from: Hello, you have been registered on <?= Yii::$app->urlManager->hostInfo ?>
to: <?= UserManagementModule::t('front', 'Hello, you have been registered on ') . Yii::$app->urlManager->hostInfo ?>

Or better, add a value in module settings for the location of registrationEmailConfirmation.php so we can have our own message file.

**Comment by webvimark** [comment]
Hi, thank you for willing to contribute! To do this you need to create a fork and then follow this instructions https://help.github.com/articles/creating-a-pull-request/

About e-mail settings. I've added 'mailerOptions' param for module.
