### ISSUE TITLE
Not able to install through composer: check screenshot attached with..

### ISSUE THREAD

**Issue by yeahgrp** [webvimark/user-management#37]
![user-mgmt](https://cloud.githubusercontent.com/assets/1564532/6946958/6100a4a6-d8c1-11e4-8776-75943bbb8a10.jpg)

I am new to Yii, I may not know much...
Pl. let me know the problem and how could rectify it

**Comment by laotse** [comment]
Similar situation here. I found that yii2 installs with minimum-stability stable. Tried 
```
composer require --prefer-dist webvimark/module-user-management "*@dev"
```
but this fails for _webvimark/components dev-master_.

**Comment by webvimark** [comment]
Hi, I guess it's because of your minimum-stability. Check solution at the last post
http://www.yiiframework.com/forum/index.php/topic/60410-yii2-user-management-module/

**Comment by webvimark** [comment]
Changed link in above post

**Comment by gazbond** [comment]
Hey, I'm having problems here too even with minimum-stability: dev and prefer-stable: true. 
Any thoughts?
