### ISSUE TITLE
UserVisitLog Table Filter Exception when database use prefix

### ISSUE THREAD

**Issue by OleGaaa** [webvimark/user-management#38]
Hi. Sorry for my English. In UserVisitLogSearch class i found few errors. I use tablePrefix in my Db connection, and when i try filtering UserVisitLog Table, i catch Exception. Fix this:

Original code:
<code>
public function search($params)
{
		$query = UserVisitLog::find();

		$query->joinWith(['user']);

		// Don't let non-superadmin view superadmin activity
		if ( !Yii::$app->user->isSuperadmin )
		{
			$query->andWhere(['user.superadmin'=>0]);
		}

		$dataProvider = new ActiveDataProvider([
			'query' => $query,
			'pagination' => [
				'pageSize' => Yii::$app->request->cookies->getValue('_grid_page_size', 20),
			],
			'sort'=>[
				'defaultOrder'=>['id'=> SORT_DESC],
			],
		]);

		if (!($this->load($params) && $this->validate())) {
			return $dataProvider;
		}

		if ( $this->visit_time )
		{
			$tmp = explode(' - ', $this->visit_time);
			if ( isset($tmp[0], $tmp[1]) )
			{
				$query->andFilterWhere(['between','user_visit_log.visit_time', strtotime($tmp[0]), strtotime($tmp[1])]);
			}
		}

		$query->andFilterWhere([
			'user_visit_log.id' => $this->id,
		]);

        	$query->andFilterWhere(['like', 'user.username', $this->user_id])
			->andFilterWhere(['like', 'user_visit_log.ip', $this->ip])
			->andFilterWhere(['like', 'user_visit_log.os', $this->os])
			->andFilterWhere(['like', 'user_visit_log.browser', $this->browser])
			->andFilterWhere(['like', 'user_visit_log.language', $this->language]);

		return $dataProvider;
	}
</code>

my fix:

<code>
public function search($params)
	{
		$query = UserVisitLog::find();

		$query->joinWith(['user']);

		// Don't let non-superadmin view superadmin activity
		if ( !Yii::$app->user->isSuperadmin )
		{
			$query->andWhere(['user.superadmin'=>0]);
		}

		$dataProvider = new ActiveDataProvider([
			'query' => $query,
			'pagination' => [
				'pageSize' => Yii::$app->request->cookies->getValue('_grid_page_size', 20),
			],
			'sort'=>[
				'defaultOrder'=>['id'=> SORT_DESC],
			],
		]);

		if (!($this->load($params) && $this->validate())) {
			return $dataProvider;
		}

		if ( $this->visit_time )
		{
			$tmp = explode(' - ', $this->visit_time);
			if ( isset($tmp[0], $tmp[1]) )
			{
				$query->andFilterWhere(['between',UserVisitLog::tableName().'.visit_time', strtotime($tmp[0]), strtotime($tmp[1])]);
			}
		}

		$query->andFilterWhere([
			UserVisitLog::tableName().'.id' => $this->id,
		]);

        	$query->andFilterWhere(['like', UserVisitLog::tableName().'.username', $this->user_id])
			->andFilterWhere(['like', UserVisitLog::tableName().'.ip', $this->ip])
			->andFilterWhere(['like', UserVisitLog::tableName().'.os', $this->os])
			->andFilterWhere(['like', UserVisitLog::tableName().'.browser', $this->browser])
			->andFilterWhere(['like', UserVisitLog::tableName().'.language', $this->language]);

		return $dataProvider;
	}
</code>

**Comment by webvimark** [comment]
Thank you for pointing at this ixxue
