### ISSUE TITLE
Registration and password recovery not accessible by default  

### ISSUE THREAD

**Issue by MGHollander** [webvimark/user-management#39]
Hi,

Awesome extension! I'm only wondering myself why I get redirected to the login page when I go the the registration or recover password pages. And the logout page is visible in the Ghost menu while I'm not logged in.

**Comment by phdcoder** [comment]
its the default behavior, you have to include the action in the freeaccess property. Is in the docs!!

**Comment by webvimark** [comment]
Hi, sorry for late answer.
phdcoder is correct that by default registration and password recovery not available. You have to add they routes to **commontPermission** rule

**Comment by GiacomoK** [comment]
Sorry to answer to this closed post, but I have the same problem and I don't know where and what update I have to do.

The docs are not clear about that.

**Comment by hindus-pl** [comment]
I can't find it either.
