### ISSUE TITLE
Installation problem 

### ISSUE THREAD

**Issue by davidscr** [webvimark/user-management#41]
I have an issue installing your extension. I've installed it with the composer, changed my configs, migrated and edited the SiteController. But I keep getting this error on the fresh installation:

Getting unknown property: webvimark\modules\UserManagement\components\UserConfig::displayName

I tried it for 5 times now, but it isn't working yet.

**Comment by webvimark** [comment]
Where did you try to access **displayName** ? User model doesn't has one

**Comment by davidscr** [comment]
Nevermind, i just figured it out. There was a code snipped from another user-extensions that was throwing this exception.

Yii::$app->user->displayName

This is so embarassing dude :laughing: But thanks for your really fast answer. :+1:

**Comment by webvimark** [comment]
You are welcome =)
