### ISSUE TITLE
Demo code for app-basic

### ISSUE THREAD

**Issue by laotse** [webvimark/user-management#43]
Is there probably some minimal demo code, e.g. integration of *user-management* into the *app-basic* template?

I guess that the explanations in the *README.md* are sufficient for the experienced *yii2* user, but I'm new to the framework. My first attempt came down to an error, where once again I have no idea what exactly I missed.

Just for information: in *webvimark/module-user-management/models/rbacDB/Route.php* function *isInCommonPermission()* line 231 I get: *Trying to get property of non-object*. As it seems *(new Query())->select('child')* yields no instance.

**Comment by webvimark** [comment]
Hi, there is no minimal demo code, because once you go through installation guide you already have it integrated =)
And yes, README file is quite bad right now.

Can you show full error ?

**Comment by laotse** [comment]
What I did:

I followed all steps inthe *README.md* including the migration. All worked nicely.

I added the *'ghost-access'* behavior to *SiteController::behaviors()*. Would I have had to remove the *'access'* behavior first?

In *views/layouts/main.php* I inserted the sample *GhostMenu::widget* code in between the breadcrumbs and the content. Just to get an idea which HTML would be generated.

Then I browsed to the root page and got (sorry no hilighting):

**Error**
**PHP Notice – yii\base\ErrorException**
**Trying to get property of non-object**

1. in /var/www/yii2/vendor/webvimark/module-user-management/models/rbacDB/Route.php at line 231

(231 is the line starting ->from(Yii::$app-> ...)

```php
         */
        protected static function isInCommonPermission($currentFullRoute)
        {
            $commonRoutes = Yii::$app->cache->get('__commonRoutes');
     
            if ( $commonRoutes === false )
            {
                $commonRoutesDB = (new Query())
                    ->select('child')
                    ->from(Yii::$app->getModule('user-management')->auth_item_child_table)
                    ->where(['parent'=>Yii::$app->getModule('user-management')->commonPermissionName])
                    ->column();
     
                $commonRoutes = Route::withSubRoutes($commonRoutesDB, ArrayHelper::map(Route::find()->asArray()->all(), 'name', 'name'));
     
                Yii::$app->cache->set('__commonRoutes', $commonRoutes, 3600);
            }
     
            return in_array($currentFullRoute, $commonRoutes);
```
2. in /var/www/yii2/vendor/webvimark/module-user-management/components/GhostAccessControl.php – webvimark\modules\UserManagement\models\rbacDB\Route::isFreeAccess() at line 45

```php
            {
                return true;
            }
     
            $route = '/' . $action->uniqueId;
     
            if ( Route::isFreeAccess($route, $action) )
            {
                return true;
            }
     
            if ( Yii::$app->user->isGuest )
            {
```
3. in /var/www/yii2/vendor/yiisoft/yii2/base/ActionFilter.php – webvimark\modules\UserManagement\components\GhostAccessControl::beforeAction() at line 71

4. in /var/www/yii2/vendor/yiisoft/yii2/base/Component.php – yii\base\ActionFilter::beforeFilter() at line 538

5. in /var/www/yii2/vendor/yiisoft/yii2/base/Component.php – call_user_func() at line 538

6. in /var/www/yii2/vendor/yiisoft/yii2/base/Controller.php – yii\base\Component::trigger() at line 259

7. in /var/www/yii2/vendor/yiisoft/yii2/web/Controller.php – yii\base\Controller::beforeAction() at line 108

8. in /var/www/yii2/vendor/yiisoft/yii2/base/Controller.php – yii\web\Controller::beforeAction() at line 149

9. in /var/www/yii2/vendor/yiisoft/yii2/base/Module.php – yii\base\Controller::runAction() at line 455

10. in /var/www/yii2/vendor/yiisoft/yii2/web/Application.php – yii\base\Module::runAction() at line 83

11. in /var/www/yii2/vendor/yiisoft/yii2/base/Application.php – yii\web\Application::handleRequest() at line 375

12. in /var/www/yii2/web/index.php – yii\base\Application::run() at line 12
     
```php
    require(__DIR__ . '/../vendor/autoload.php');
    require(__DIR__ . '/../vendor/yiisoft/yii2/Yii.php');
     
    $config = require(__DIR__ . '/../config/web.php');
     
    (new yii\web\Application($config))->run();
```

Yii Framework/2.0.3

**Comment by webvimark** [comment]
Check please step 1 in configuration guide. It looks like your app cannot find this module in config

```php
'modules'=>[
    'user-management' => [
        'class' => 'webvimark\modules\UserManagement\UserManagementModule',

        // Here you can set your handler to change layout for any controller or action
        // Tip: you can use this event in any module
        'on beforeAction'=>function(yii\base\ActionEvent $event) {
                if ( $event->action->uniqueId == 'user-management/auth/login' )
                {
                    $event->action->controller->layout = 'loginLayout.php';
                };
            },
    ],
],
```

**Comment by laotse** [comment]
Ooops, seems like I reverted the change. I'm not yet settled how to best use git in this setup.

Anyhow, now I get:

*Invalid Configuration – yii\base\InvalidConfigException*
*The configuration for the "modules" component must contain a "class" element.*

1. in /var/www/yii2/vendor/yiisoft/yii2/di/ServiceLocator.php at line 202
2. in /var/www/yii2/vendor/yiisoft/yii2/di/ServiceLocator.php – yii\di\ServiceLocator::set('modules', ['user-management' => ['class' => 'webvimark\modules\UserManagement...', 'on beforeAction' => Closure]]) at line 258

The code throwing the exception expects a 'class' entry directly under 'modules', which obviously is not there. But from the examples and documentation I neither think it should.

**Comment by webvimark** [comment]
Show me you config file, just cut all sensitive data like passwords

**Comment by laotse** [comment]
This hopefully is a vanilla base-application with only the modifications from user-management:

**web.php**
```php
$params = require(__DIR__ . '/params.php');

$config = [
    'id' => 'basic',
    'basePath' => dirname(__DIR__),
    'bootstrap' => ['log'],
    'components' => [
        'request' => [
            // !!! insert a secret key in the following (if it is empty) - this is required by cookie validation
            'cookieValidationKey' => '*******************************************',
        ],
        'cache' => [
            'class' => 'yii\caching\FileCache',
        ],
        'user' => [
            'class' => 'webvimark\modules\Useranagement\components\UserConfig',
            // comment, if you don't want user logging
            'on afterLogin' => function($event) {
                \webvimark\modules\UserManagement\models\UserVisitingLog::newVisitor($event->identity->id);
            }
        ],
        'errorHandler' => [
            'errorAction' => 'site/error',
        ],
        'mailer' => [
            'class' => 'yii\swiftmailer\Mailer',
            // send all mails to a file by default. You have to set
            // 'useFileTransport' to false and configure a transport
            // for the mailer to send real emails.
            'useFileTransport' => true,
        ],
        'modules'=>[
	    	'user-management' => [
	        	'class' => 'webvimark\modules\UserManagement\UserManagementModule',

	        	// Here you can set your handler to change layout for any controller or action
	        	// Tip: you can use this event in any module
	        	'on beforeAction'=>function(yii\base\ActionEvent $event) {
	            	if ( $event->action->uniqueId == 'user-management/auth/login' ) {
	                	$event->action->controller->layout = 'loginLayout.php';
	                };
	            },
	    	],
		],
        'log' => [
            'traceLevel' => YII_DEBUG ? 3 : 0,
            'targets' => [
                [
                    'class' => 'yii\log\FileTarget',
                    'levels' => ['error', 'warning'],
                ],
            ],
        ],
        'db' => require(__DIR__ . '/db.php'),
    ],
    'params' => $params,
];

if (YII_ENV_DEV) {
    // configuration adjustments for 'dev' environment
    $config['bootstrap'][] = 'debug';
    $config['modules']['debug'] = 'yii\debug\Module';

    $config['bootstrap'][] = 'gii';
    $config['modules']['gii'] = 'yii\gii\Module';
}

return $config;
```

**params.php**
```php
return [
    'adminEmail' => 'admin@example.com',
];
```

**db.php**
```php
return [
    'class' => 'yii\db\Connection',
    'dsn' => 'mysql:host=mydbhost.example.com;dbname=yii_test',
    'username' => 'yii_tester',
    'password' => 'ATestPassword',
    'charset' => 'utf8',
];
```

**Comment by webvimark** [comment]
Ok, I see now =) You put 'modules' category in 'components' category. It should be on the same level in array

**Comment by laotse** [comment]
Yeah, that was it. Many thanks for the help!

**Comment by webvimark** [comment]
You are welcome :)
