### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by mohanmoorthy** [webvimark/user-management#45]
Hi there,

  I am trying to download composer require --prefer-dist webvimark/module-user-management "*"
but it returns 

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package webvimark/module-user-management could not be found in any version, there may be a typo in the package name.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.

Read <http://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

**Comment by webvimark** [comment]
Hi, I guess it's because of your minimum-stability. Check solution at the last post
http://www.yiiframework.com/forum/index.php/topic/60410-yii2-user-management-module/page__p__270905#entry270905

**Comment by mohanmoorthy** [comment]
Yep. It's working great now. thank you
