### ISSUE TITLE
Class problem on Linux

### ISSUE THREAD

**Issue by davidscr** [webvimark/user-management#47]
I migrated my application one to one at t linux system. Now I'm getting this error:

Class webvimark\modules\UserManagement\components\GhostAccessControl does not exist

What to do?

Thanks :relaxed:

**Comment by dvdkrgr** [comment]
Just for your information: There was something wrong in my .gitignore and composer configuration. The vendor directory was ignored by my .gitignore and on the server i'm running composer install / update. After fixing my composer.json everything was fine.
