### ISSUE TITLE
API Document by this USER-MANAGEMENT vendor

### ISSUE THREAD

**Issue by lukBarros** [webvimark/user-management#52]
### API Document by this USER-MANAGEMENT vendor

Hi mans.

I missed a standard API phpdoc for example, for advanced developers who want to further explore all that is possible within that vendor .

The readme.md is mostly very basic examples and use cases with halpers , advanced topics of using components , etc.

There are plans to generate an API , if not , can I try to generate this and somehow distribute integrated with current documentation (on github )

**Comment by webvimark** [comment]
Hi, I have plans to extend documentation, but with my poor time-management I don't know when it will be done =)

So if you want to contribute to documentation or generate API doc, then you are most welcome !

**Comment by lukBarros** [comment]
Hi man, I work in the phpdoc gen for projetc. I have usage in the my internal projects on yii2 and have hosting it online in the my server in Dallas (IBM SoftLayer). OK?

**Comment by lukBarros** [comment]
See http://169.54.161.163/opensource.id5.com.br/yii2/webvimark/user-management/apidoc/html/

**Comment by lukBarros** [comment]
see outher version http://169.54.161.163/opensource.id5.com.br/yii2/webvimark/user-management/apidoc/html/v2/

**Comment by webvimark** [comment]
Hi, sorry for late answer. I guess you disabled this documentation ? =)

**Comment by lukBarros** [comment]
Sorry, i work in dns names for it...

Fix access in http://opensource.id5.com.br/webvimark/doc/

**Comment by webvimark** [comment]
Thank you! Added link to readme

**Comment by lukBarros** [comment]
Ok man, lets rock!
