### ISSUE TITLE
Redirect to specified page after login

### ISSUE THREAD

**Issue by dvdkrgr** [webvimark/user-management#55]
Hey, how can I use the on afterLogin method to redirect to a page of my choose?

Like that:

      'on afterLogin' => function($event) {
        \webvimark\modules\UserManagement\models\UserVisitLog::newVisitor($event->identity->id);

        CODE HERE TO REDIRECT TO admin/index FOR EXAMPLE

      }

Can't figure it out.

Thanks for any help!

**Comment by webvimark** [comment]
Sorry for the late reply, I doubt that you still need this, but here it is :)

```php
'on afterLogin' => function($event) {
				\webvimark\modules\UserManagement\models\UserVisitLog::newVisitor($event->identity->id);

				header('Location: '.Url::to(['/admin/index', true]));
				die();
			}
```
