### ISSUE TITLE
Refresh-Routes in Advance Template.

### ISSUE THREAD

**Issue by jsgilvcb** [webvimark/user-management#56]
Thanks for your module. It is the best one.
I am implementing this module in and advance template with:
- Frontend
- Backend
- Console
- Api

I have DefaultController in all instances so i am confuse how can the refresh routes cam be for diferent scenarios. 
Example: 
Admin can use DefaultController index action when loggin in backend.
In front end DefaultController do a diferent routine so i want to set only certains users to access those routes.

Can you help. Maybe i can explain better my sittuation.
Thanks

**Comment by webvimark** [comment]
Hi, sorry for the late response.

Unfortunately installing this module in advanced application template is not a trivial task, because you actually have several different apps.
So, can't help you right now :(
