### ISSUE TITLE
Install module throw composer filed

### ISSUE THREAD

**Issue by poremchuk** [webvimark/user-management#58]
Hi, guys! I'm trying to install the module into my Yii2 project and unfortunately got an error like "The requested package could not be found in any version". How I can resolve this issue? 

P.S.
Other modules are installed just fine.

![13 06](https://cloud.githubusercontent.com/assets/3364472/8144826/7d387512-11f7-11e5-9f0f-ec18240d8382.png)

**Comment by webvimark** [comment]
Hi, I guess it's because of your minimum-stability. Check solution at the last post
http://www.yiiframework.com/forum/index.php/topic/60410-yii2-user-management-module/page__p__270905#entry270905

**Comment by poremchuk** [comment]
Thanks!

On 15 June 2015 at 11:16, webvimark <notifications@github.com> wrote:

> Hi, I guess it's because of your minimum-stability. Check solution at the
> last post
>
> http://www.yiiframework.com/forum/index.php/topic/60410-yii2-user-management-module/page__p__270905#entry270905
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/webvimark/user-management/issues/58#issuecomment-111974322>
> .
>



-- 
З повагою, Поремчук Євгеній Володимирович
Мій сайто-блог - www.indev.org.ua
Web-інженерія - www.aisogroup.com <http://www.AisoGroup.com>
Початитись зі-мною:  ICQ  - 321 324 376
