### ISSUE TITLE
Access control

### ISSUE THREAD

**Issue by zolton007** [webvimark/user-management#64]
Hi!
Sorry for my english :)
I installed your module in my application (Yii-basic).
My config:
web.php
```
...    
'components' => [
    'user' => [
        'class' => 'webvimark\modules\UserManagement\components\UserConfig',
        'on afterLogin' => function($event) {
            \webvimark\modules\UserManagement\models\UserVisitLog::newVisitor($event->identity->id);
        }		
    ],
]
....
'modules'=>[
    'user-management' => [
        'class' => 'webvimark\modules\UserManagement\UserManagementModule',
        'on beforeAction'=>function(yii\base\ActionEvent $event)
        {
            if ( $event->action->uniqueId == 'user-management/auth/login' )
            {
                $event->action->controller->layout = 'loginLayout.php';
            };
        },
    ],
],
```
My controller:
SiteController.php
```
namespace app\controllers;

use Yii;
use webvimark\components\BaseController;

class SiteController extends BaseController
{
    public $freeAccess = false;
    ...
    public function actionIndex()
    {
        return $this->render('index');
    }
    ...
}
```
Although the property freeAccess set false, an authorized user can not access it.
1) How to restrict access to controllers and actions?
2) How to do to earn helpers User::hasPermission, User::hasRole etc? (i have error "Class 'app\controllers\User' not found")
3) How to set a default role for guest user?

**Comment by webvimark** [comment]
1) Add routes to permissions, permissions to roles and roles to users =)
2) it's not 'app\controllers\User' , but 'webvimark\modules\UserManagement\models\User'
3) There are no default role for guest, but rather 'commonPermission' that is contain access to routes which is available to everyone

**Comment by webvimark** [comment]
Hi =)

**Comment by zolton007** [comment]
> Add routes to permissions, permissions to roles and roles to users =)
This is understandable, but why then properties freeAccess freeAccessActions?
>it's not 'app\controllers\User' , but 'webvimark\modules\UserManagement\models\User'
Yes, the connection in the controller webvimark\modules\UserManagement\models\User solved the problem. Error "Class 'app\controllers\User' not found" appeared, if I wasn't connected :)
> There are no default role for guest, but rather 'commonPermission' that is contain access to routes which is available to everyone
OK, thank you! 
ps and thank you for Your work!

**Comment by webvimark** [comment]
freeAccess and freeAccessActions useful if you this controller/action available for everyone. But suddenly became lazy and do not want to write migrations that add this controller/action to 'commonPermission' =)

**Comment by zolton007** [comment]
> There are no default role for guest, but rather 'commonPermission' that is contain access to routes which is available to everyone
 	
So, I have the SiteController. In "common permission" /site/* not marked, however, not an authorized user has access to this controller. How to restrict access? Add a check on the actions (like User::hasRole)?

**Comment by zolton007** [comment]
Another question! How to create a permission like "delete OWN news"?

**Comment by webvimark** [comment]
Hi, you cannot create such *business* rule to be filtered by routes.
So you have to check by yourself if user creator is === current user  :)
