### ISSUE TITLE
Cannot register

### ISSUE THREAD

**Issue by Boco10** [webvimark/user-management#65]
Hello,

I can't sign up if i am using the page as guest.

<a href="http://tinypic.com?ref=34j6j46" target="_blank"><img src="http://i62.tinypic.com/34j6j46.png" border="0" alt="Image and video hosting by TinyPic"></a>

Here is an img about what i see if i try to login. Also an issue, if i try to go to /user-management/auth/registration it's redirect me to login.

What's can be the issue?

**Comment by zolton007** [comment]
1)Log in as superadmin 
2)Go to admin -> permissions-> common permission and set the checkbox on /user-management/auth/*

**Comment by Boco10** [comment]
O.m.g 

Thanks.
