### ISSUE TITLE
GhostHtml::a issue on login page

### ISSUE THREAD

**Issue by stefanguse** [webvimark/user-management#7]
Hello!
I seem to be missing something since I can't get the registration and password-recovery links in the view login.php to show up. As far as I can tell the problem seems to be in Route::isInCommonPermission

In the AuthController I've added
public $freeAccessActions = ['login','registration','password-recovery'];

Furthermore I've added a new permission group 'commonPermission' and a permission 'registration' with the route '/user-management/auth/registration'.

However
$commonRoutesDB = (new Query())
				->select('child')
				->from(Yii::$app->getModule('user-management')->auth_item_child_table)
				->where(['parent'=>Yii::$app->getModule('user-management')->commonPermissionName])
				->column();
will never produce a result since the values for 'paren't and 'child' in auth_item_child are 'registration' and '/user-management/auth/registration' but the Query looks for 'commonPermission'

What did I miss? Thanks in advance!

**Comment by stefanguse** [comment]
Well, should have maybe thought about it a minute longer.
Read the comments more thoroughly and realised that the route has to be added to the permission 'commonPermission', not to a permission group of that name. Sorry about that

**Comment by webvimark** [comment]
You read faster than I'm writing =)
