### ISSUE TITLE
Redirect to Login after Session Timeout

### ISSUE THREAD

**Issue by Stefan39** [webvimark/user-management#71]
How can i redirect to Login after a session is timeout?

I want to use /site/login with copied ActiveForm and own styles with this module, therefore i have change into SiteController the Login Action to /site/login.

**Comment by webvimark** [comment]
Hi, you can set following parameter in your config -> components -> user

```php
'loginUrl' => ['site/login']
```

**Comment by Stefan39** [comment]
Hm, without function.

i have put the code into config/web.php into components:

    'components' => [
        'user' => [
            'class' => 'webvimark\modules\UserManagement\components\UserConfig',
            'loginUrl' => ['site/login'],
            'on afterLogin' => function($event) {
                \webvimark\modules\UserManagement\models\UserVisitLog::newVisitor($event->identity->id);
            }
        ],
    ]

**Comment by dvdkrgr** [comment]
You should check if your LocationController contains the following inside the behaviors() method:

      'ghost-access' => [
        'class' => 'webvimark\modules\UserManagement\components\GhostAccessControl',
      ],

**Comment by Stefan39** [comment]
I use a BaseController, where i have this into the behaviours method. Is it ok or need it into every own behaviour?

**Comment by dvdkrgr** [comment]
Give it a try and write down your results. It depends on how your BaseController is configured. Maybe there is something wrong with it. Optionally you can paste the relevant code here so we can have a look at it.

**Comment by webvimark** [comment]
Hi, is this problem still valid ?

**Comment by Stefan39** [comment]
Hi,

the behaviour on BaseController with ghost-access will not work. If i put it on the used controller this will work.
