### ISSUE TITLE
registration access

### ISSUE THREAD

**Issue by ivanchenkoandriy** [webvimark/user-management#72]
/vendor/webvimark/module-user-management/controllers/AuthController.php
public $freeAccessActions = ['login', 'logout', 'confirm-registration-email', 'registration'];

**Comment by dvdkrgr** [comment]
What is your issue???

**Comment by ivanchenkoandriy** [comment]
need add 'registration'

**Comment by webvimark** [comment]
There are plenty of ways to do it (add route to common permission, replace controller via classMap, implement your own login).
Not every project needs registration.

**Comment by aikon2** [comment]
maybe you need
`'modules' => [
        'user-management' => [
              'enableRegistration' => true,`
