### ISSUE TITLE
Can't install with composer

### ISSUE THREAD

**Issue by pitonn** [webvimark/user-management#74]
Hi, I have error. Yii 2.0.5

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package webvimark/module-user-management could not be found in any version, there may be a typo in the package name.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

**Comment by snizhok** [comment]
http://www.yiiframework.com/forum/index.php/topic/61995-solved-cant-install-webvimarkmodule-user-management/

**Comment by haritasj** [comment]
I too have problem installing with composer but a different one. I get following error 
[UnexpectedValueException]                                              
  Could not parse version constraint <=2.*: Invalid version string "2.*"

I added 
"minimum-stability": "dev",
 "prefer-stable" : true,

to composer.json. Also I updated composer with 

composer self-update
 
but still no luck.

**Comment by webvimark** [comment]
Do you have problems with installing other exstenstions ?
And paste your composer code here

**Comment by haritasj** [comment]
I had problem with other extensions too. Looks like main problem is what is being discussed here

https://github.com/francoispluchino/composer-asset-plugin/issues/129

I have't checked it properly. Will do it and update here.
