### ISSUE TITLE
Bulk Actions For Activate/Deactivate User Don't seem to work

### ISSUE THREAD

**Issue by sganz** [webvimark/user-management#76]
Just playing with the plug in and so far very nice!

I may have found a minor issue, in that on the User management page (The grid) the bulk drop down that allows Delete, Activate, and De-activate only works for Delete.

![yiiauth-bug](https://cloud.githubusercontent.com/assets/5179047/9503038/8934a648-4be9-11e5-878f-ee51725b4db2.jpg)

**Comment by webvimark** [comment]
Thank you for pointing at this bug =)
Fixed it, but you have to update --with-dependencies

**Comment by sganz** [comment]
Thanks will give it a go.

**Comment by sganz** [comment]
Just did a 'composer update --with-dependencies and seemed to update OK with these results -
...
 - Updating webvimark/components dev-master (63c6ec6 => 782cb6e)
    Checking out 782cb6ec7a4dc1a27389504cdfe9e15d0c47f04d

  - Updating webvimark/module-user-management dev-master (dcb7b15 => bced9d7)
    Checking out bced9d76f1b787d5416b71d8a18dfd24c0e4620a


Now when running the user page I get an exception tossed - 

Unable to locate message source for category 'widgets/GridBulkActions/app'

Anything else I needed to do?

Thanks

Sandy

**Comment by sganz** [comment]
Could the code that is using Yii's translate  -
Current code...
Url::to(['bulk-activate', 'attribute'=>'status'])=>GridBulkActions::t(**'app'**, 'Activate'),

Maybe Updated To ????
Url::to(['bulk-activate', 'attribute'=>'status'])=>GridBulkActions::t(**'back'**, 'Activate'),

Sandy

**Comment by webvimark** [comment]
Once more please =)
```
composer update --with-dependencies
```

**Comment by sganz** [comment]
Updated seems good on initial check out. 

Thanks for the quick fix. The Module works very will on testing. 

And big thanks for the excellent module!

**Comment by webvimark** [comment]
Thank you for feedback :)
