### ISSUE TITLE
Editing Permission etc. impossible

### ISSUE THREAD

**Issue by stjcottbus** [webvimark/user-management#77]
Problem:
Attempt to edit "Description" of existing permission without touching the "Code"
always responses: Code "..." has already been taken.

As this is correct for a new item it shouldn't happen for an existing item.

Any idea what's going wrong?

**Comment by margori** [comment]
I confirm this bug.

**Comment by stjcottbus** [comment]
@margori:
Didn't evaluated further because I'm rolling my own solution ... 
but maybe it's related to the fact that "AbstractItem::validateUniqueName"
uses "Route::find" instead of "static::find".
That might be the reason ...

**Comment by webvimark** [comment]
Fixed
