### ISSUE TITLE
Password Recovery, Login, Logout - Action

### ISSUE THREAD

**Issue by stjcottbus** [webvimark/user-management#78]
After experimenting a bit I think there are some (minor) issues in the AuthController:
- login-Action is free accessible, but i think it should only be accessible by not 
  already authenticated users (Yii::$app->user->isGuest)
- logut-Action is free accessible, but i think it should only be accessible by  
  already authenticated users (!Yii::$app->user->isGuest)
- password-recovery-Action is _not_ free accessible but should be as anyone who is already 
  logged in should never need it :-)

**Comment by cesao** [comment]
I solved it this way: putting a following code on module config.

'on beforeAction' => function(yii\base\ActionEvent $event) {
    
                 if ($event->action->uniqueId == 'user-management/auth/password-recovery') {
                    $event->action->controller->freeAccessActions[]='password-recovery';
                    
                }
            },

**Comment by webvimark** [comment]
Working as intended :)

Login action has condition

```php
if ( !Yii::$app->user->isGuest )
{
	return $this->goHome();
}
```

Logout action just redirect everyone to home page. Plus as a bonus logout logged users :)

Password recovery disabled by default, because not every website needs it. And ones who need it could add it to "commonPermission"
