### ISSUE TITLE
I am lost in user permision

### ISSUE THREAD

**Issue by alopezbnt** [webvimark/user-management#79]
I see in the code 

User::canRoute

But allways get forbidden when call by controller 

<?php

namespace app\controllers;

use Yii;
use yii\web\Controller;
use webvimark\components\BaseController;

class AdminController extends Controller
{

    public $freeAccess = false;

    public function behaviors()
    {
        return [
            'ghost-access'=> [
                'class' => 'webvimark\modules\UserManagement\components\GhostAccessControl',
            ]
                ];

    }

    public function actionIndex()
    {

        return $this->render('index');
    }

}
~

**Comment by webvimark** [comment]
Hey, you should extend your AdminController from BaseController
