### ISSUE TITLE
The requested package webvimark/module-user-management could not be found in any version

### ISSUE THREAD

**Issue by Robot72** [webvimark/user-management#8]
Sorry that I take your time. 
I have changed in the global configuration json. I used the command "require" according to the manual. I have all the same error. I did the configuration of the composer.json of project, as shown in the picture.
![2015-01-12 12 50 23](https://cloud.githubusercontent.com/assets/5987937/5701349/f7b92080-9a5a-11e4-9d01-5c3e4818f91c.png)

I tried all methods from http://getcomposer.org/doc/articles/troubleshooting.md
the problem is not solved.

**Comment by webvimark** [comment]
Hi, I guess it's because of your minimum-stability. Check solution at the last post
http://www.yiiframework.com/forum/index.php/topic/60410-yii2-user-management-module/

**Comment by Robot72** [comment]
Thank you!
