### ISSUE TITLE
How to filter user list by account wise

### ISSUE THREAD

**Issue by sasiarjun** [webvimark/user-management#80]
I have the table like user_account fields are userid, accountid, Here I want to filter the users list by account wise, Currently it showing all users to all accounts i want to restrict users by account wise. Please help me to sove this

**Comment by webvimark** [comment]
I'm sorry, but this question is not related to the module.

I short - your should add to your UserAccountSearch something like this

```php
$query->andWhere(['accountid'=>number_of_account]);
```
