### ISSUE TITLE
Unable to update a Permission or any AbstractItem because of validateUniqueName

### ISSUE THREAD

**Issue by devsuitup** [webvimark/user-management#86]
Hi,

We can't udpate a permission or any AbstractItemdue to
`webvimark\modules\UserManagement\models\rbacDB\AbstractItem`

	`/**
	 * @inheritdoc
	 */
	public function rules()
	{
		return [
			[...]
			['name', 'validateUniqueName'], // line 179
		];
	}`

What I though of doing was something like `['name', 'validateUniqueName', 'on'=>'create'],` and realized that both create and update were under the `webInput` scenario, which makes it impossible to treat that validation rule separately right ?

**Comment by byphone** [comment]
Hi, 

I have this problem too, i 'm not able to update the name of an item, with the error : code already exist.

**Comment by webvimark** [comment]
Fixed
