### ISSUE TITLE
Multiple Apps Sharing DB

### ISSUE THREAD

**Issue by sganz** [webvimark/user-management#93]
Using the user-management and create another app that uses the same user tables as generated by the first app (Same Users). 

Is this something that can work?  

My concern is that if both apps have a route such as  /tree-editor but are actually each apps specific instance (In their own webpath) will their be any differentiation when I set up access permissions. Right now for common pages such as 'about' I see only one rule when I refresh (tried from both apps).

Not sure if any way to do this, but an App Prefix on the permissions would allow.

I would just set up another DB but since it's common to both apps as are the users seems like the wrong way to go as I would have to manage a different set of access rules for them.

Any comments would be most helpful!

Sandy

**Comment by webvimark** [comment]
Hi, i'ts kind of tricky, because this module do not intended to work in 2 different apps at once. But you may try to pass "false" to Route::refreshRoutes($deleteUnusedRoutes = true). It will allow you to share routes between apps

**Comment by sganz** [comment]
Sorry for the late reply!

Yeah, I have been using a version that has the refresh only option showing and it works OK, but tricky to set up.  About the only way that I can think of making it all work is to have each application id that would have to be added to a lot of places and to the db's. Might be a lot of work for lazy me. I think the Advanced Template folks might have a similar issue except they have a frontend/backend issue instead of different apps. 

In any case thanks for the reply!

Sandy
