### ISSUE TITLE
User should have only one role, not multiple. How to?

### ISSUE THREAD

**Issue by webmalinka** [webvimark/user-management#98]
For example, I have user, which has role "Editor". But from the RBAC interface we can assign additional roles. How to restrict system to assign multiple roles to user?

**Comment by webvimark** [comment]
Now you can set "userCanHaveMultipleRoles" parameter to "false" in config and web interface will allow you to set only 1 role to user

**Comment by webmalinka** [comment]
Thanks, it works. But how about to restrict multiple roles systemwide, not only in view form?

**Comment by webvimark** [comment]
But why do you need it system-wide ? Your admins, moderators and other users can work only with web interface. Migrations and other stuff that can assign roles will be written only by developers.
