### ISSUE TITLE
Error in module without controllers

### ISSUE THREAD

**Issue by amoracr** [webvimark/user-management#99]
Hello, I got an error while applying the migrations of your module. 
![webvimark user-management error](https://cloud.githubusercontent.com/assets/15234820/11691139/56926a9a-9e5f-11e5-9133-0b0c3f7e65c6.png)

I use several modules of kartik-v, some of them are widgets only, I mean those modules don't have controllers. As far I understand your module lists all other modules and tries to get their routes, but somehow it doesn't skip modules without controllers.

Let me know if you need more details.

Thanks for the module, it's very helpful.

**Comment by webvimark** [comment]
Hi, check it now

**Comment by amoracr** [comment]
I updated the module,  the migration worked like a charm. Thanks a lot.
